---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/xbxkhdmy/public_html/wp-content/themes/slm-theme/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH/style.css
    - /bin/cp functions.php $DEPLOYPATH/functions.php
    - if [ -d assets ]; then /bin/cp -R assets $DEPLOYPATH/; fi
